# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CoronaChartApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoronaChartApp
  pod 'Alamofire', '~> 5.5'
  pod 'Charts'
  target 'CoronaChartAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoronaChartAppUITests' do
    # Pods for testing
  end

end
